/** 本地化 文字 文件 */
export enum LangFile {
    no = 'no',// 无
    en = 'en',// 英文
    jp = 'jp',// 日文
    kr = 'kr',// 韩文
    zh = 'zh',// 繁体中文
};

/** 本地化 文字 字段 */
export const LangChars = {
    loading: "loading",
    guide_tip: "guide_tip",
    guide_back: "guide_back",
    guide_refresh: "guide_refresh",
    guide_ice: "guide_ice",
    guide_magnet: "guide_magnet",
    guide_clock: "guide_clock",
    over_timeout_title: "over_timeout_title",
    over_timeout_desc: "over_timeout_desc",
    over_timeout_playon: "over_timeout_playon",
    over_timeout_giveup: "over_timeout_giveup",
    over_nospace_title: "over_nospace_title",
    over_nospace_gobackgood: "over_nospace_gobackgood",
    exit_confirm_desc: "exit_confirm_desc",
    exit_confirm_restart: "exit_confirm_restart",
    exit_confirm_giveup: "exit_confirm_giveup",
    pause_title: "pause_title",
    pause_resume: "pause_resume",
    pause_quit: "pause_quit",
    exit_title: "exit_title",
    exit_desc: "exit_desc",
    exit_resume: "exit_resume",
    exit_quit: "exit_quit",
    win_finish: "win_finish",
    win_next: "win_next",
    hour: "hour",
    minite: "minite",
    second: "second",
    Level: "Level",
    Bank: "Bank",
    Home: "Home",
    Shop: "Shop",
    Theme: "Theme",
    Areas: "Areas",
    Reward: "Reward",
    Commodity: "Commodity",
    Collection: "Collection",
    CONTINUE: "CONTINUE",
    setting_title: "setting_title",
    setting_language: "setting_language",
    gameBefore_level: "gameBefore_level",
    gameBefore_wins: "gameBefore_wins",
    gameBefore_play: "gameBefore_play",
    gameBefore_chose: "gameBefore_chose",
    continuesChallenge_title: "continuesChallenge_title",
    continuesChallenge_desc: "continuesChallenge_desc",
    continuesChallenge_times: "continuesChallenge_times",
    boxLevel_title: "boxLevel_title",
    boxLevel_desc: "boxLevel_desc",
    boxXingxing_title: "boxXingxing_title",
    boxXingxing_desc: "boxXingxing_desc",
    boxGood_title: "boxGood_title",
    boxGood_button: "boxGood_button",
    tapToClaim: "tapToClaim",
    tapToContinue: "tapToContinue",
    goldCollection: "goldCollection",
    addCoin_title: "addCoin_title",
    addCoin_desc_0: "addCoin_desc_0",
    addCoin_desc_1: "addCoin_desc_1",
    addCoin_watch: "addCoin_watch",
    addLife_free: "addLife_free",
    addLife_title: "addLife_title",
    addLife_nextFill: "addLife_nextFill",
    addLife_reFill: "addLife_reFill",
    bank_title: "bank_title",
    bank_desc: "bank_desc",
    SHOP: "SHOP",
    ShopBeginnersBundle: "ShopBeginnersBundle",
    ShopElfGiftBox: "ShopElfGiftBox",
    ShopPrincessTreasure: "ShopPrincessTreasure",
    ShopShiningBundle: "ShopShiningBundle",
    ShopMikoGiftPack: "ShopMikoGiftPack",
    ShopQueenTreasure: "ShopQueenTreasure",
    LimitedOffer: "LimitedOffer",
    RemoveAds: "RemoveAds",
    MostPopular: "MostPopular",
    BestPrice: "BestPrice",
    Goods: "Goods",
    Moment: "Moment",
    Doll: "Doll",
    Handbag: "Handbag",
    Satchel: "Satchel",
    Ball: "Ball",
    Christmas: "Christmas",
    shoes: "shoes",
    Cap: "Cap",
    Flower: "Flower",
    Electronics: "Electronics",
    GreenPlants: "GreenPlants",
    Toy: "Toy",
    adsNo: "adsNo",
    adsRemovePopup: "adsRemovePopup",
    adsNetworkNo: "adsNetworkNo",
    adsNetworkElse: "adsNetworkElse",
    adsNotReady: "adsNotReady",
    Daily: "Daily",
    dailyChallenge_January: "dailyChallenge_January",
    dailyChallenge_February: "dailyChallenge_February",
    dailyChallenge_March: "dailyChallenge_March",
    dailyChallenge_April: "dailyChallenge_April",
    dailyChallenge_May: "dailyChallenge_May",
    dailyChallenge_June: "dailyChallenge_June",
    dailyChallenge_July: "dailyChallenge_July",
    dailyChallenge_August: "dailyChallenge_August",
    dailyChallenge_September: "dailyChallenge_September",
    dailyChallenge_October: "dailyChallenge_October",
    dailyChallenge_November: "dailyChallenge_November",
    dailyChallenge_December: "dailyChallenge_December",
    dailyChallenge_Monday: "dailyChallenge_Monday",
    dailyChallenge_Tuesday: "dailyChallenge_Tuesday",
    dailyChallenge_Wednesday: "dailyChallenge_Wednesday",
    dailyChallenge_Thursday: "dailyChallenge_Thursday",
    dailyChallenge_Friday: "dailyChallenge_Friday",
    dailyChallenge_Saturday: "dailyChallenge_Saturday",
    dailyChallenge_Sunday: "dailyChallenge_Sunday",
    dailyChallenge_play: "dailyChallenge_play",
    dailyChallenge_win_1: "dailyChallenge_win_1",
    dailyChallenge_win_3: "dailyChallenge_win_3",
    dailyChallenge_win_10: "dailyChallenge_win_10",
    dailyChallenge_win_28: "dailyChallenge_win_28",
    logon_reward_daily: "logon_reward_daily",
    logon_reward_claim: "logon_reward_claim",
    logon_reward_day_1: "logon_reward_day_1",
    logon_reward_day_2: "logon_reward_day_2",
    logon_reward_day_3: "logon_reward_day_3",
    logon_reward_day_4: "logon_reward_day_4",
    logon_reward_day_5: "logon_reward_day_5",
    logon_reward_day_6: "logon_reward_day_6",
    logon_reward_day_7: "logon_reward_day_7",
    areas_1:"areas_1",
    areas_2:"areas_2",
    areas_3:"areas_3",
    areas_4:"areas_4",
    areas_5:"areas_5",
    areas_6:"areas_6",
    areas_7:"areas_7",
    areas_8:"areas_8",
    areas_9:"areas_9",
    areas_10:"areas_10",
    areas_11:"areas_11",
    areas_12:"areas_12",
    areas_13:"areas_13",
    areas_14:"areas_14",
    areas_15:"areas_15",
    achieve_1: "achieve_1",
    achieve_2: "achieve_2",
    achieve_3: "achieve_3",
    achieve_4: "achieve_4",
    achieve_5: "achieve_5",
    achieve_6: "achieve_6",
    achieve_7: "achieve_7",
    achieve_8: "achieve_8",
    achieve_9: "achieve_9",
    achieve_10: "achieve_10",
    achieve_11: "achieve_11",
    achieve_12: "achieve_12"
};

/** 本地化 图片 名字 */
export const LangImg = {
    word_logo_title: "word_logo_title",
    word_win_title: "word_win_title",
};